### PR TITLE
[OFFAPPS-485] Display correct urls for multibrand hostmapped Help Centers

### PR DESCRIPTION
**Pull request by danielbreves**
:koala: 

Looks like the HC API now returns host-mapped urls.

cc @zendesk/quokka 

### References
- https://zendesk.atlassian.net/browse/OFFAPPS-485

### Risks
- HC urls may be incorrect

### CODE REVIEW

**Comment by svizzari** [comment]
:joy_cat: :+1:

**Comment by adammw** [comment]
:+1:

**Comment by adammw** [comment]
@bastien @libo Any idea if there's another API we can access the full article from on the agent subdomain? At the moment we have to limit to displaying the search result body for hostmapped and non-default brands.

**Comment by bastien** [comment]
Hi @adammw, I'm not sure what the issue is here, can you clarify the problem?
We only have the one API (/api/v2/help_center/articles/:id).

We are working on a new app for all the content (aka the Knowledge Bank), and will be offering an API for that at some point, but that won't be before a while.

**Pull request merged**
