### PR TITLE
[OFFAPPS-663] updated helpText for nb_entries setting

### PR DESCRIPTION
**Pull request by pmgrove**
:v:

/cc @zendesk/vegemite

### Description
I have updated a string in the en.yml file to include a min value for the nb_entries settings. @ydrain, @injuhwang is this the correct way to do this for an app setting help text string?

### References
* JIRA: https://zendesk.atlassian.net/browse/OFFAPPS-663

### Risks

### CODE REVIEW

**Comment by ydrain** [comment]
We typically ask to create a new key (https://zendesk.atlassian.net/wiki/x/xQL-B). We can work around it for this one.

:+1:

**Comment by timbertson** [comment]
:+1:

**Comment by sandlerr** [comment]
how often do people try to display zero or fewer results?

**Comment by tobico** [comment]
:+1:

**Comment by danielbreves** [comment]
:+1:

**Pull request merged**
